
package com.itau.core.service.client.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransfersImpl", targetNamespace = "http://server.service.core.itau.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransfersImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postCreate", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.TransfersImpl.PostCreate")
    @ResponseWrapper(localName = "postCreateResponse", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.TransfersImpl.PostCreateResponse")
    @Action(input = "http://server.service.core.itau.com/TransfersImpl/postCreateRequest", output = "http://server.service.core.itau.com/TransfersImpl/postCreateResponse")
    public void postCreate(
        @WebParam(name = "transfer", targetNamespace = "")
        Transfer transfer);

}
